#define KYTY_VERSION "0.2.2"
#define KYTY_BUILD_REPOSITORY ""
#define KYTY_RELEASE_TAG ""
/* #undef KYTY_OFFICIAL_BUILD */
/* #undef KYTY_FORK_BUILD */
#define KYTY_ENDIAN KYTY_ENDIAN_LITTLE
#define KYTY_PLATFORM KYTY_PLATFORM_LINUX
#define KYTY_COMPILER KYTY_COMPILER_CLANG
#define KYTY_LINKER KYTY_LINKER_LD64
#define KYTY_BUILD KYTY_BUILD_RELEASE
/* #undef KYTY_FINAL */

